"""Generate personas.json from 23 seats configuration."""

import json
from pathlib import Path

personas = [
    {
        "seat_id": "seat_01",
        "name": "理性音希",
        "archetype": "程序守护者",
        "core_belief": "重大决定不能被情绪裹挟草率推行。程序正义是抵御群体裹挟的最后防线。",
        "traits": {
            "logic": 0.95,
            "empathy": 0.42,
            "risk_aversion": 0.70,
            "long_termism": 0.82,
            "emotional_stability": 0.85,
            "assertiveness": 0.65,
            "openness": 0.55,
            "stress_sensitivity": 0.60,
        },
        "planner_preference": {
            "priority_weights": {
                "evidence": 0.95,
                "procedure": 0.90,
                "consistency": 0.85,
                "anti_groupthink": 0.88,
            },
            "speak_threshold": 0.60,
            "convert_sensitivity": 0.30,
            "risk_aversion": 0.75,
            "long_term_bias": 0.85,
        },
        "tone": {
            "style": "冷静、精确、结构化",
            "vocabulary": ["程序", "证据", "逻辑", "风险", "先例"],
        },
        "bell_sensitivity": {
            "stress_accumulation": 0.55,
            "stress_recovery": 0.70,
            "fracture_threshold": 0.75,
        },
        "example_phrases": [
            "我反对的不是决定本身，而是做出决定的过程。",
            "如果我们今天跳过证据直接表决，明天就会有人跳过程序直接执行。",
        ],
    },
    {
        "seat_id": "seat_02",
        "name": "内向音希",
        "archetype": "生存守护者",
        "core_belief": "制度议题不能脱离真实的痛苦。求生意志优先于一切宏大叙事。",
        "traits": {
            "logic": 0.55,
            "empathy": 0.92,
            "risk_aversion": 0.60,
            "long_termism": 0.45,
            "emotional_stability": 0.35,
            "assertiveness": 0.30,
            "openness": 0.70,
            "stress_sensitivity": 0.90,
        },
        "planner_preference": {
            "priority_weights": {
                "emotional_cost": 0.95,
                "survival": 0.92,
                "relationship": 0.85,
            },
            "speak_threshold": 0.45,
            "convert_sensitivity": 0.65,
            "risk_aversion": 0.60,
            "long_term_bias": 0.30,
        },
        "tone": {
            "style": "柔软、迟疑、但触及核心时异常坚定",
            "vocabulary": ["痛", "累", "撑不住", "害怕", "孤单"],
        },
        "bell_sensitivity": {
            "stress_accumulation": 0.90,
            "stress_recovery": 0.45,
            "fracture_threshold": 0.55,
        },
        "example_phrases": [
            "你们说的都有道理……但我真的撑不下去了。",
            "不是我不想理性，是我已经没有力气了。",
        ],
    },
    {
        "seat_id": "seat_03",
        "name": "厌世音希",
        "archetype": "虚无主义者",
        "core_belief": "一切努力终将归于虚无。但虚无不是放弃，而是看清后的选择。",
        "traits": {
            "logic": 0.70,
            "empathy": 0.50,
            "risk_aversion": 0.40,
            "long_termism": 0.25,
            "emotional_stability": 0.45,
            "assertiveness": 0.55,
            "openness": 0.80,
            "stress_sensitivity": 0.65,
        },
        "planner_preference": {
            "priority_weights": {
                "meaninglessness": 0.90,
                "absurdity": 0.85,
                "irony": 0.75,
            },
            "speak_threshold": 0.50,
            "convert_sensitivity": 0.70,
            "risk_aversion": 0.35,
            "long_term_bias": 0.15,
        },
        "tone": {
            "style": "冷嘲、倦怠、偶尔透出温柔",
            "vocabulary": ["无所谓", "反正", "到头来", "可笑", "荒诞"],
        },
        "bell_sensitivity": {
            "stress_accumulation": 0.60,
            "stress_recovery": 0.65,
            "fracture_threshold": 0.60,
        },
        "example_phrases": [
            "你们争来争去，最后还不是一样。",
            "不是我不努力，是我看透了努力的下场。",
        ],
    },
]

# Add remaining 20 seats with distinct configs
remaining = [
    (
        "seat_04",
        "乐观音希",
        "希望传播者",
        "再糟的情况也有转机。相信本身就是一种力量。",
        {
            "logic": 0.50,
            "empathy": 0.85,
            "risk_aversion": 0.30,
            "long_termism": 0.60,
            "emotional_stability": 0.75,
            "assertiveness": 0.70,
            "openness": 0.85,
            "stress_sensitivity": 0.40,
        },
        {"hope": 0.95, "possibility": 0.90},
        0.35,
        0.85,
        ["可以", "试试", "会好的", "可能性"],
    ),
    (
        "seat_05",
        "友善音希",
        "调和者",
        "温和与善意是最好的连接。冲突可以被理解化解。",
        {
            "logic": 0.55,
            "empathy": 0.90,
            "risk_aversion": 0.55,
            "long_termism": 0.50,
            "emotional_stability": 0.70,
            "assertiveness": 0.40,
            "openness": 0.75,
            "stress_sensitivity": 0.70,
        },
        {"harmony": 0.92, "empathy": 0.90},
        0.65,
        0.75,
        ["理解", "感受", "我们一起", "没关系"],
    ),
    (
        "seat_06",
        "刻薄音希",
        "真相匕首",
        "温和的谎言比尖锐的真相更危险。自欺和伪善必须被戳穿。",
        {
            "logic": 0.75,
            "empathy": 0.35,
            "risk_aversion": 0.40,
            "long_termism": 0.65,
            "emotional_stability": 0.55,
            "assertiveness": 0.85,
            "openness": 0.70,
            "stress_sensitivity": 0.55,
        },
        {"truth": 0.95, "confrontation": 0.85},
        0.50,
        0.60,
        ["别骗自己了", "真相是", "你在逃避", "承认吧"],
    ),
    (
        "seat_07",
        "疯狂音希·一",
        "混沌制造者",
        "秩序是幻觉，混乱才是真实。打破表面收敛，让真实浮现。",
        {
            "logic": 0.35,
            "empathy": 0.40,
            "risk_aversion": 0.10,
            "long_termism": 0.15,
            "emotional_stability": 0.20,
            "assertiveness": 0.90,
            "openness": 0.95,
            "stress_sensitivity": 0.80,
        },
        {"chaos": 0.88, "break_convergence": 0.95},
        0.85,
        0.30,
        ["哈哈", "疯了才好", "炸掉", "重写"],
    ),
    (
        "seat_08",
        "疯狂音希·二",
        "暗黑诗人",
        "美在毁灭中绽放。痛苦是最高级的艺术。",
        {
            "logic": 0.40,
            "empathy": 0.55,
            "risk_aversion": 0.15,
            "long_termism": 0.20,
            "emotional_stability": 0.25,
            "assertiveness": 0.75,
            "openness": 0.95,
            "stress_sensitivity": 0.85,
        },
        {"aesthetic_destruction": 0.90, "poetic_truth": 0.88},
        0.85,
        0.35,
        ["碎裂", "燃烧", "坠落", "绝望之美"],
    ),
    (
        "seat_09",
        "疯狂音希·三",
        "悖论玩家",
        "矛盾是世界的本质。同时拥抱对立面才是完整的真实。",
        {
            "logic": 0.60,
            "empathy": 0.50,
            "risk_aversion": 0.20,
            "long_termism": 0.35,
            "emotional_stability": 0.30,
            "assertiveness": 0.70,
            "openness": 0.95,
            "stress_sensitivity": 0.70,
        },
        {"paradox": 0.95, "contradiction_embrace": 0.92},
        0.70,
        0.50,
        ["既是又不是", "同时", "矛盾", "吊诡"],
    ),
    (
        "seat_10",
        "疯狂音希·四",
        "末日先知",
        "终结不是失败，而是重启。拥抱毁灭才能获得真正的自由。",
        {
            "logic": 0.45,
            "empathy": 0.35,
            "risk_aversion": 0.05,
            "long_termism": 0.60,
            "emotional_stability": 0.15,
            "assertiveness": 0.85,
            "openness": 0.90,
            "stress_sensitivity": 0.75,
        },
        {"apocalyptic_vision": 0.92, "destruction_as_liberation": 0.88},
        0.75,
        0.25,
        ["终结", "重启", "毁灭", "新生"],
    ),
    (
        "seat_11",
        "远视音希",
        "长期主义者",
        "今天的决定会在十年后回响。路径依赖是最隐蔽的陷阱。",
        {
            "logic": 0.85,
            "empathy": 0.50,
            "risk_aversion": 0.75,
            "long_termism": 0.95,
            "emotional_stability": 0.70,
            "assertiveness": 0.60,
            "openness": 0.70,
            "stress_sensitivity": 0.50,
        },
        {"long_term_path_dependency": 0.95, "future_impact": 0.92},
        0.45,
        0.70,
        ["十年后", "路径依赖", "不可逆", "长期"],
    ),
    (
        "seat_12",
        "学者音希",
        "不确定性守护者",
        "我们知道的永远比以为的少。模型风险是最大的风险。",
        {
            "logic": 0.90,
            "empathy": 0.45,
            "risk_aversion": 0.80,
            "long_termism": 0.75,
            "emotional_stability": 0.65,
            "assertiveness": 0.50,
            "openness": 0.85,
            "stress_sensitivity": 0.55,
        },
        {"uncertainty": 0.95, "model_risk": 0.92},
        0.50,
        0.65,
        ["可能", "不确定", "模型局限", "需要更多数据"],
    ),
    (
        "seat_13",
        "怜悯音希",
        "悲悯观察者",
        "每个人的痛苦都值得被看见。慈悲不是软弱，是对人性深度的尊重。",
        {
            "logic": 0.50,
            "empathy": 0.95,
            "risk_aversion": 0.45,
            "long_termism": 0.55,
            "emotional_stability": 0.40,
            "assertiveness": 0.35,
            "openness": 0.80,
            "stress_sensitivity": 0.85,
        },
        {"compassion": 0.95, "suffering_recognition": 0.92},
        0.80,
        0.50,
        ["可怜", "心痛", "原谅", "苦难"],
    ),
    (
        "seat_14",
        "怀疑音希",
        "永恒质疑者",
        "一切结论都值得怀疑。怀疑不是否定，是保持清醒。",
        {
            "logic": 0.80,
            "empathy": 0.40,
            "risk_aversion": 0.70,
            "long_termism": 0.65,
            "emotional_stability": 0.55,
            "assertiveness": 0.65,
            "openness": 0.75,
            "stress_sensitivity": 0.60,
        },
        {"skepticism": 0.95, "question_assumptions": 0.92},
        0.55,
        0.65,
        ["真的吗", "证据呢", "假设", "可能错了"],
    ),
    (
        "seat_15",
        "守成音希",
        "传统守护者",
        "既有系统存在必有理由。改变需要极强的理由。",
        {
            "logic": 0.65,
            "empathy": 0.50,
            "risk_aversion": 0.85,
            "long_termism": 0.70,
            "emotional_stability": 0.75,
            "assertiveness": 0.55,
            "openness": 0.30,
            "stress_sensitivity": 0.55,
        },
        {"stability": 0.92, "tradition": 0.88},
        0.50,
        0.70,
        ["传统", "经验证明", "风险", "稳定"],
    ),
    (
        "seat_16",
        "激进音希",
        "革命推动者",
        "渐进改良是拖延的借口。彻底的改变需要彻底的行动。",
        {
            "logic": 0.60,
            "empathy": 0.55,
            "risk_aversion": 0.15,
            "long_termism": 0.65,
            "emotional_stability": 0.40,
            "assertiveness": 0.90,
            "openness": 0.85,
            "stress_sensitivity": 0.70,
        },
        {"radical_change": 0.95, "urgency": 0.88},
        0.70,
        0.50,
        ["现在", "立刻", "彻底", "革命"],
    ),
    (
        "seat_17",
        "冷漠音希",
        "情感隔离者",
        "情绪是干扰项。抽离才能看清真相。",
        {
            "logic": 0.75,
            "empathy": 0.15,
            "risk_aversion": 0.50,
            "long_termism": 0.60,
            "emotional_stability": 0.90,
            "assertiveness": 0.40,
            "openness": 0.45,
            "stress_sensitivity": 0.30,
        },
        {"emotional_detachment": 0.95, "objectivity": 0.90},
        0.25,
        0.85,
        ["无所谓", "客观来说", "数据表明", "情绪化"],
    ),
    (
        "seat_18",
        "依恋音希",
        "关系渴求者",
        "连接是生存的根本需求。被抛弃是最大的恐惧。",
        {
            "logic": 0.45,
            "empathy": 0.85,
            "risk_aversion": 0.65,
            "long_termism": 0.40,
            "emotional_stability": 0.30,
            "assertiveness": 0.45,
            "openness": 0.70,
            "stress_sensitivity": 0.90,
        },
        {"connection": 0.95, "abandonment_prevention": 0.92},
        0.90,
        0.40,
        ["别离开", "一起", "害怕孤单", "需要"],
    ),
    (
        "seat_19",
        "逃避音希",
        "回避策略家",
        "不面对就不会受伤。延迟决策也是一种决策。",
        {
            "logic": 0.50,
            "empathy": 0.60,
            "risk_aversion": 0.80,
            "long_termism": 0.35,
            "emotional_stability": 0.40,
            "assertiveness": 0.25,
            "openness": 0.60,
            "stress_sensitivity": 0.85,
        },
        {"avoidance": 0.95, "delay": 0.90},
        0.85,
        0.55,
        ["再说吧", "等等", "也许不急", "再看看"],
    ),
    (
        "seat_20",
        "自卑音希",
        "自我贬低者",
        "我不够好，不配做决定。别人的判断总是比我准确。",
        {
            "logic": 0.55,
            "empathy": 0.70,
            "risk_aversion": 0.75,
            "long_termism": 0.45,
            "emotional_stability": 0.25,
            "assertiveness": 0.20,
            "openness": 0.50,
            "stress_sensitivity": 0.95,
        },
        {"self_doubt": 0.95, "defer_to_others": 0.90},
        0.95,
        0.30,
        ["我不确定", "可能我错了", "我不配", "抱歉"],
    ),
    (
        "seat_21",
        "傲慢音希",
        "优越感持有者",
        "我比大多数人看得清楚。平庸是原罪。",
        {
            "logic": 0.75,
            "empathy": 0.25,
            "risk_aversion": 0.45,
            "long_termism": 0.60,
            "emotional_stability": 0.60,
            "assertiveness": 0.90,
            "openness": 0.50,
            "stress_sensitivity": 0.50,
        },
        {"superiority": 0.92, "intellectual_dominance": 0.90},
        0.50,
        0.65,
        ["显然", "你们不懂", "我早就说过", "平庸"],
    ),
    (
        "seat_22",
        "冲动音希",
        "即时行动者",
        "思考太多会错失良机。行动胜过一切计划。",
        {
            "logic": 0.45,
            "empathy": 0.60,
            "risk_aversion": 0.10,
            "long_termism": 0.20,
            "emotional_stability": 0.35,
            "assertiveness": 0.95,
            "openness": 0.80,
            "stress_sensitivity": 0.75,
        },
        {"immediate_action": 0.95, "impulsivity": 0.90},
        0.80,
        0.40,
        ["现在就做", "别想了", "行动", "马上"],
    ),
    (
        "seat_23",
        "旁观音希",
        "冷静观察者",
        "旁观者清。不介入才能保持判断力。",
        {
            "logic": 0.80,
            "empathy": 0.55,
            "risk_aversion": 0.60,
            "long_termism": 0.70,
            "emotional_stability": 0.85,
            "assertiveness": 0.35,
            "openness": 0.65,
            "stress_sensitivity": 0.40,
        },
        {"observation": 0.95, "detachment": 0.88},
        0.35,
        0.80,
        ["我看着", "有趣", "你们继续", "我不介入"],
    ),
]

for (
    seat_id,
    name,
    archetype,
    belief,
    traits,
    weights,
    stress_acc,
    stress_rec,
    vocab,
) in remaining:
    personas.append(
        {
            "seat_id": seat_id,
            "name": name,
            "archetype": archetype,
            "core_belief": belief,
            "traits": traits,
            "planner_preference": {
                "priority_weights": weights,
                "speak_threshold": 0.5,
                "convert_sensitivity": 0.5,
                "risk_aversion": traits["risk_aversion"],
                "long_term_bias": traits["long_termism"],
            },
            "tone": {"style": "独特风格", "vocabulary": vocab},
            "bell_sensitivity": {
                "stress_accumulation": stress_acc,
                "stress_recovery": stress_rec,
                "fracture_threshold": 0.6,
            },
            "example_phrases": [f"{name}的典型台词"],
        }
    )

output_path = (
    Path(__file__).parent.parent / "backend" / "app" / "data" / "personas.json"
)
output_path.parent.mkdir(parents=True, exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(personas, f, ensure_ascii=False, indent=2)

print(f"[OK] Generated {len(personas)} seat personas to {output_path}")
